# 00. PyTorch Fundamentals Exercises



In [1]:
# No code solution (reading)

### 1. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch


# Create random tensor
torch.rand(7,7)

tensor([[0.4127, 0.6385, 0.2622, 0.2295, 0.5955, 0.6789, 0.5832],
        [0.4070, 0.2638, 0.7251, 0.2609, 0.0389, 0.9888, 0.6255],
        [0.9250, 0.2089, 0.1162, 0.5572, 0.5645, 0.2662, 0.7862],
        [0.0359, 0.0344, 0.2136, 0.4949, 0.0578, 0.6923, 0.8177],
        [0.9919, 0.7513, 0.2929, 0.4269, 0.1456, 0.2422, 0.5484],
        [0.4891, 0.6049, 0.5373, 0.8634, 0.4139, 0.0537, 0.7793],
        [0.3880, 0.4293, 0.9871, 0.1739, 0.4362, 0.6838, 0.7627]])

### 2. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
tensor_1 = torch.rand(1,7)
tensor_2 = tensor_1.T


# Perform matrix multiplication
mul = torch.matmul(tensor_1,tensor_2)
mul

tensor([[2.6128]])

### 3. Set the random seed to `0` and do 2 & 3 over again.



In [4]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)


# Create two random tensors
x = torch.rand(size = (7,1))
y = x.T


# Matrix multiply tensors
z = torch.matmul(x,y)
size = z.size()
z , size

(tensor([[0.2463, 0.3812, 0.0439, 0.0655, 0.1526, 0.3147, 0.2432],
         [0.3812, 0.5902, 0.0680, 0.1014, 0.2362, 0.4871, 0.3765],
         [0.0439, 0.0680, 0.0078, 0.0117, 0.0272, 0.0561, 0.0434],
         [0.0655, 0.1014, 0.0117, 0.0174, 0.0406, 0.0837, 0.0647],
         [0.1526, 0.2362, 0.0272, 0.0406, 0.0945, 0.1949, 0.1507],
         [0.3147, 0.4871, 0.0561, 0.0837, 0.1949, 0.4021, 0.3108],
         [0.2432, 0.3765, 0.0434, 0.0647, 0.1507, 0.3108, 0.2402]]),
 torch.Size([7, 7]))

### 4. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
RANDOM_SEED = 1234
torch.cuda.is_available()
torch.cuda.manual_seed(RANDOM_SEED)


### 5. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [6]:
# Set random seed
RANDOM_SEED = 1234
torch.manual_seed(RANDOM_SEED)

# Check for access to GPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Create two random tensors on GPU
tensors = torch.rand((2,3),device = device)
torch.cuda.manual_seed(RANDOM_SEED)
tensors_1 = torch.rand((2,3),device = device)
tensors

tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')

In [7]:
tensors_1

tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')


### 6. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [8]:
# Perform matmul on tensor_A and tensor_B
tensors_2 = tensors.T
mul = torch.matmul(tensors , tensors_2)
print(mul)
print(mul.size())


tensor([[0.9792, 0.8358],
        [0.8358, 1.4578]], device='cuda:0')
torch.Size([2, 2])


### 7. Find the maximum and minimum values of the output of 7.

In [9]:
# Find max
torch.max(mul)

# Find min
torch.min(mul)


tensor(0.8358, device='cuda:0')

### 8. Find the maximum and minimum index values of the output of 7.

In [10]:
# Find arg max
torch.argmax(mul)


# Find arg min
torch.argmin(mul)


tensor(1, device='cuda:0')


### 9. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [14]:
# Set seed
RANDOM_SEED = 7
# Create random tensor
tensor = torch.rand(size=(1,1,1,10))
# Remove single dimensions
tensor_1 = tensor.squeeze()
# Print out tensors and their shapes
print(tensor,tensor.shape)

tensor([[[[0.7837, 0.5631, 0.7749, 0.8208, 0.2793, 0.6817, 0.2837, 0.6567,
           0.2388, 0.7313]]]]) torch.Size([1, 1, 1, 10])


In [15]:
print(tensor_1,tensor_1.shape)

tensor([0.7837, 0.5631, 0.7749, 0.8208, 0.2793, 0.6817, 0.2837, 0.6567, 0.2388,
        0.7313]) torch.Size([10])
