In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

#Introduction to tensors

Creating tensors

In [2]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
#Get the tensor back to int
scalar.item()

7

In [4]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [5]:
vector.ndim

1

In [6]:
vector.shape

torch.Size([2])

In [7]:
#Matrix

MATRIX = torch.tensor([[5,1],
                        [8,1]])
MATRIX

tensor([[5, 1],
        [8, 1]])

In [8]:
MATRIX.shape

torch.Size([2, 2])

In [9]:
MATRIX.ndim

2

In [10]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [11]:
TENSOR.shape

torch.Size([1, 3, 3])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR1 = torch.tensor([[[[1,2,3,4],
                          [5,6,7,8],
                          [9,10,11,12],
                          [13,14,15,16]]]])

In [14]:
TENSOR1.shape

torch.Size([1, 1, 4, 4])

#RANDOM TENSORS

Random tensors are important because the way many neural networks learn is that they start with full of random numbers and then adjust the random numbers to better represent the data

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [15]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2608, 0.1948, 0.0604, 0.5929],
        [0.1215, 0.3596, 0.0974, 0.9202],
        [0.3620, 0.3287, 0.5092, 0.0797]])

In [16]:
#create a random tensor with similar to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height #width #color channels
random_image_size_tensor

tensor([[[0.4855, 0.5701, 0.5999],
         [0.9465, 0.6320, 0.1165],
         [0.5953, 0.3896, 0.8593],
         ...,
         [0.9815, 0.6082, 0.1542],
         [0.7064, 0.6762, 0.2301],
         [0.7602, 0.2899, 0.0316]],

        [[0.9384, 0.8991, 0.9804],
         [0.2863, 0.9491, 0.8833],
         [0.1727, 0.6890, 0.0752],
         ...,
         [0.8295, 0.8181, 0.2289],
         [0.8782, 0.6362, 0.6932],
         [0.3513, 0.9404, 0.9057]],

        [[0.3323, 0.4807, 0.5864],
         [0.9293, 0.6432, 0.6658],
         [0.7944, 0.8943, 0.5537],
         ...,
         [0.8531, 0.2399, 0.1432],
         [0.8361, 0.2549, 0.2272],
         [0.5199, 0.4553, 0.4240]],

        ...,

        [[0.9018, 0.4681, 0.7891],
         [0.7294, 0.3253, 0.4420],
         [0.8644, 0.0542, 0.2930],
         ...,
         [0.7734, 0.5037, 0.5968],
         [0.2753, 0.1434, 0.5191],
         [0.7126, 0.5850, 0.8809]],

        [[0.9334, 0.5263, 0.1638],
         [0.2115, 0.8754, 0.1854],
         [0.

In [17]:
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Zeros and ones

In [18]:
zeros = torch.zeros(2,2)
zeros

tensor([[0., 0.],
        [0., 0.]])

In [19]:
ones = torch.ones(3,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

Creating a range of tensors and tensor-s like

In [20]:
range = torch.range(0,10)
range

<ipython-input-20-91a60021e470>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  range = torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [21]:
range = torch.arange(0,10)
range

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
step_value = torch.arange(0,10,2)
step_value

tensor([0, 2, 4, 6, 8])

#Tensor datatypes

In [23]:
#float32 Tensor
float_32_tensor = torch.tensor([1.0,2.0,3.0])
float_32_tensor

tensor([1., 2., 3.])

In [24]:
float_32_tensor.dtype

torch.float32

In [25]:
#conversion of float32 to float16
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [26]:
#int datatype
int_32_tensor = torch.tensor([1,2,3],dtype=torch.int32)
int_32_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [27]:
float_tensor__int_tensor = float_32_tensor*int_32_tensor
float_tensor__int_tensor

tensor([1., 4., 9.])

In [28]:
float_tensor__int_tensor.shape

torch.Size([3])

In [29]:
float_tensor__int_tensor.device

device(type='cpu')

In [30]:
some_tensor = torch.rand([5,4])
print(some_tensor)
print(f"The shape of the some_tensor: {some_tensor.shape}")
print(f"The device which is operating some_tensor: {some_tensor.device}")
print(f"The ndim of the some_tensor: {some_tensor.ndim}")
print(f"The dtype of the some_tensor : {some_tensor.dtype}")

tensor([[0.2251, 0.3644, 0.3627, 0.0699],
        [0.5052, 0.5258, 0.4280, 0.8218],
        [0.8844, 0.7372, 0.5021, 0.2003],
        [0.2432, 0.7384, 0.6183, 0.4004],
        [0.2507, 0.9016, 0.1670, 0.6086]])
The shape of the some_tensor: torch.Size([5, 4])
The device which is operating some_tensor: cpu
The ndim of the some_tensor: 2
The dtype of the some_tensor : torch.float32


#Manipulating tensors

Tensor operations include :
* Addition
* Multiplication
* Division
* Subtraction
* Matrix multiplication

For manipulating tensors there are inbuilt in funcs like torch.add , torch.sub , torch.mul , torch.div

In [31]:
tensor_1 = torch.rand([3,4])
tensor_2 = torch.rand([3,4])
tensor_add = tensor_1 + tensor_2
tensor_add

tensor([[1.1470, 1.1662, 1.6624, 1.0771],
        [1.3142, 0.8498, 0.9787, 1.0173],
        [1.0337, 1.5307, 0.8941, 0.7955]])

In [32]:
torch.add(tensor_1,tensor_2)

tensor([[1.1470, 1.1662, 1.6624, 1.0771],
        [1.3142, 0.8498, 0.9787, 1.0173],
        [1.0337, 1.5307, 0.8941, 0.7955]])

In [33]:
tensor_mul = tensor_1*tensor_2
tensor_mul

tensor([[0.1505, 0.3320, 0.6820, 0.1848],
        [0.3433, 0.1669, 0.2392, 0.2433],
        [0.0384, 0.5441, 0.0642, 0.0563]])

In [34]:
torch.mul(tensor_1,10)

tensor([[1.5113, 4.9381, 7.3671, 2.1419],
        [3.5962, 5.4172, 4.7395, 3.8441],
        [9.9509, 9.6948, 8.1535, 7.1705]])

In [35]:
torch.mul(tensor_2,20)

tensor([[19.9173, 13.4475, 18.5147, 17.2575],
        [19.0911,  6.1626, 10.0946, 12.6582],
        [ 0.7722, 11.2236,  1.5749,  1.5691]])

In [36]:
tensor_div = tensor_1/tensor_2
tensor_div

tensor([[ 0.1518,  0.7344,  0.7958,  0.2482],
        [ 0.3767,  1.7581,  0.9390,  0.6074],
        [25.7718,  1.7276, 10.3544,  9.1396]])

In [37]:
torch.div(tensor_1,tensor_2)

tensor([[ 0.1518,  0.7344,  0.7958,  0.2482],
        [ 0.3767,  1.7581,  0.9390,  0.6074],
        [25.7718,  1.7276, 10.3544,  9.1396]])

In [38]:
tensor_sub = tensor_1-tensor_2
tensor_sub

tensor([[-0.8447, -0.1786, -0.1890, -0.6487],
        [-0.5949,  0.2336, -0.0308, -0.2485],
        [ 0.9565,  0.4083,  0.7366,  0.6386]])

In [39]:
torch.sub(tensor_1,tensor_2)

tensor([[-0.8447, -0.1786, -0.1890, -0.6487],
        [-0.5949,  0.2336, -0.0308, -0.2485],
        [ 0.9565,  0.4083,  0.7366,  0.6386]])

There are two ways of performing multiplication in deep learning and neural networks

1.Element wise

2.Matrix multiplication(dot product)

1.Element wise

In [40]:
tensor_1 = torch.tensor([1,2,3])
tensor_2 = torch.tensor([2,4,6])


In [41]:
torch.mul(tensor_1,tensor_2)

tensor([ 2,  8, 18])

Matrix Multiplication

In [42]:
torch.matmul(tensor_1,tensor_2)

tensor(28)

In [43]:
torch.__version__

'2.1.0+cu121'

#One of the most common errors in Deep Learning : shape errors

The two main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match

(3,2) * (3,2) won't work here but (2,3) * (3,2) works here

2. The **outer dimensions** - shape

(2,3) * (3,2) => (2,2) shape

(3,2) * (2,3) => (3,3) shape





In [47]:
mat_mul = torch.matmul(torch.rand([2,3]) , torch.rand([3,2]))
mat_mul

tensor([[0.3664, 0.4977],
        [0.6242, 0.6299]])

In [48]:
mat_mul.shape

torch.Size([2, 2])

This is 2 dimensional

In [50]:
mat_mul = torch.matmul(torch.rand([3,2]) , torch.rand([2,3]))
mat_mul

tensor([[0.6250, 0.7214, 0.2446],
        [0.6565, 0.8195, 0.5072],
        [0.7372, 0.8976, 0.4779]])

In [51]:
mat_mul.shape

torch.Size([3, 3])

In [52]:
#This is 3 dimensional matrix