In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

#Introduction to tensors

Creating tensors

In [2]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
#Get the tensor back to int
scalar.item()

7

In [4]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [5]:
vector.ndim

1

In [6]:
vector.shape

torch.Size([2])

In [7]:
#Matrix

MATRIX = torch.tensor([[5,1],
                        [8,1]])
MATRIX

tensor([[5, 1],
        [8, 1]])

In [8]:
MATRIX.shape

torch.Size([2, 2])

In [9]:
MATRIX.ndim

2

In [10]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [11]:
TENSOR.shape

torch.Size([1, 3, 3])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR1 = torch.tensor([[[[1,2,3,4],
                          [5,6,7,8],
                          [9,10,11,12],
                          [13,14,15,16]]]])

In [14]:
TENSOR1.shape

torch.Size([1, 1, 4, 4])

#RANDOM TENSORS

Random tensors are important because the way many neural networks learn is that they start with full of random numbers and then adjust the random numbers to better represent the data

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [15]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5940, 0.0626, 0.6214, 0.9347],
        [0.8137, 0.4053, 0.9139, 0.2210],
        [0.7845, 0.4735, 0.5853, 0.0069]])

In [16]:
#create a random tensor with similar to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height #width #color channels
random_image_size_tensor

tensor([[[0.2946, 0.6351, 0.5422],
         [0.0116, 0.5269, 0.9106],
         [0.9455, 0.0295, 0.3021],
         ...,
         [0.9833, 0.2824, 0.4855],
         [0.9665, 0.5560, 0.7593],
         [0.8399, 0.8804, 0.8531]],

        [[0.4492, 0.5865, 0.3816],
         [0.9803, 0.7074, 0.8205],
         [0.7904, 0.1680, 0.0046],
         ...,
         [0.8369, 0.4524, 0.0958],
         [0.4404, 0.3435, 0.1700],
         [0.2799, 0.1278, 0.4204]],

        [[0.9536, 0.6115, 0.4732],
         [0.3104, 0.0947, 0.3205],
         [0.0684, 0.6650, 0.1100],
         ...,
         [0.9660, 0.9552, 0.9333],
         [0.2054, 0.2581, 0.8598],
         [0.8701, 0.9624, 0.7938]],

        ...,

        [[0.8810, 0.3763, 0.8355],
         [0.2536, 0.8975, 0.7127],
         [0.2306, 0.2077, 0.5697],
         ...,
         [0.0424, 0.1652, 0.7686],
         [0.0268, 0.4884, 0.3542],
         [0.8785, 0.5032, 0.0976]],

        [[0.3263, 0.2452, 0.7429],
         [0.1469, 0.8440, 0.7567],
         [0.

In [17]:
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Zeros and ones

In [18]:
zeros = torch.zeros(2,2)
zeros

tensor([[0., 0.],
        [0., 0.]])

In [19]:
ones = torch.ones(3,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

Creating a range of tensors and tensor-s like

In [20]:
range = torch.range(0,10)
range

<ipython-input-20-91a60021e470>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  range = torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [21]:
range = torch.arange(0,10)
range

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
step_value = torch.arange(0,10,2)
step_value

tensor([0, 2, 4, 6, 8])

#Tensor datatypes

In [23]:
#float32 Tensor
float_32_tensor = torch.tensor([1.0,2.0,3.0])
float_32_tensor

tensor([1., 2., 3.])

In [24]:
float_32_tensor.dtype

torch.float32

In [25]:
#conversion of float32 to float16
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [26]:
#int datatype
int_32_tensor = torch.tensor([1,2,3],dtype=torch.int32)
int_32_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [27]:
float_tensor__int_tensor = float_32_tensor*int_32_tensor
float_tensor__int_tensor

tensor([1., 4., 9.])

In [28]:
float_tensor__int_tensor.shape

torch.Size([3])

In [29]:
float_tensor__int_tensor.device

device(type='cpu')

In [30]:
some_tensor = torch.rand([5,4])
print(some_tensor)
print(f"The shape of the some_tensor: {some_tensor.shape}")
print(f"The device which is operating some_tensor: {some_tensor.device}")
print(f"The ndim of the some_tensor: {some_tensor.ndim}")
print(f"The dtype of the some_tensor : {some_tensor.dtype}")

tensor([[0.0963, 0.4234, 0.2975, 0.1325],
        [0.6429, 0.0799, 0.0487, 0.1396],
        [0.4052, 0.4944, 0.1177, 0.9137],
        [0.2855, 0.2691, 0.1732, 0.3795],
        [0.5163, 0.3657, 0.6532, 0.0377]])
The shape of the some_tensor: torch.Size([5, 4])
The device which is operating some_tensor: cpu
The ndim of the some_tensor: 2
The dtype of the some_tensor : torch.float32


#Manipulating tensors

Tensor operations include :
* Addition
* Multiplication
* Division
* Subtraction
* Matrix multiplication

For manipulating tensors there are inbuilt in funcs like torch.add , torch.sub , torch.mul , torch.div

In [31]:
tensor_1 = torch.rand([3,4])
tensor_2 = torch.rand([3,4])
tensor_add = tensor_1 + tensor_2
tensor_add

tensor([[0.9519, 0.7781, 1.7510, 1.5459],
        [0.4394, 1.3811, 0.2571, 1.3335],
        [1.6590, 1.0172, 1.0965, 0.5841]])

In [32]:
torch.add(tensor_1,tensor_2)

tensor([[0.9519, 0.7781, 1.7510, 1.5459],
        [0.4394, 1.3811, 0.2571, 1.3335],
        [1.6590, 1.0172, 1.0965, 0.5841]])

In [33]:
tensor_mul = tensor_1*tensor_2
tensor_mul

tensor([[0.1486, 0.1121, 0.7569, 0.5858],
        [0.0483, 0.4754, 0.0029, 0.3945],
        [0.6839, 0.1181, 0.1437, 0.0370]])

In [34]:
torch.mul(tensor_1,10)

tensor([[1.9671, 1.9086, 9.7351, 6.6517],
        [2.1755, 6.5158, 2.4537, 8.9043],
        [8.9389, 1.3362, 9.4427, 0.7222]])

In [35]:
torch.mul(tensor_2,20)

tensor([[15.1043, 11.7448, 15.5504, 17.6139],
        [ 4.4379, 14.5912,  0.2355,  8.8619],
        [15.3019, 17.6706,  3.0442, 10.2371]])

In [36]:
tensor_div = tensor_1/tensor_2
tensor_div

tensor([[ 0.2605,  0.3250,  1.2521,  0.7553],
        [ 0.9804,  0.8931, 20.8384,  2.0096],
        [ 1.1683,  0.1512,  6.2038,  0.1411]])

In [37]:
torch.div(tensor_1,tensor_2)

tensor([[ 0.2605,  0.3250,  1.2521,  0.7553],
        [ 0.9804,  0.8931, 20.8384,  2.0096],
        [ 1.1683,  0.1512,  6.2038,  0.1411]])

In [38]:
tensor_sub = tensor_1-tensor_2
tensor_sub

tensor([[-0.5585, -0.3964,  0.1960, -0.2155],
        [-0.0043, -0.0780,  0.2336,  0.4473],
        [ 0.1288, -0.7499,  0.7921, -0.4396]])

In [39]:
torch.sub(tensor_1,tensor_2)

tensor([[-0.5585, -0.3964,  0.1960, -0.2155],
        [-0.0043, -0.0780,  0.2336,  0.4473],
        [ 0.1288, -0.7499,  0.7921, -0.4396]])

There are two ways of performing multiplication in deep learning and neural networks

1.Element wise

2.Matrix multiplication(dot product)

1.Element wise

In [40]:
tensor_1 = torch.tensor([1,2,3])
tensor_2 = torch.tensor([2,4,6])


In [41]:
torch.mul(tensor_1,tensor_2)

tensor([ 2,  8, 18])

Matrix Multiplication

In [42]:
torch.matmul(tensor_1,tensor_2)

tensor(28)

In [43]:
torch.__version__

'2.1.0+cu121'

#One of the most common errors in Deep Learning : shape errors

The two main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match

(3,2) * (3,2) won't work here but (2,3) * (3,2) works here

2. The **outer dimensions** - shape

(2,3) * (3,2) => (2,2) shape

(3,2) * (2,3) => (3,3) shape





In [44]:
mat_mul = torch.matmul(torch.rand([2,3]) , torch.rand([3,2]))
mat_mul

tensor([[0.1807, 0.3129],
        [1.0949, 1.3488]])

In [45]:
mat_mul.shape

torch.Size([2, 2])

This is 2 dimensional

In [46]:
mat_mul = torch.matmul(torch.rand([3,2]) , torch.rand([2,3]))
mat_mul

tensor([[0.5444, 0.8199, 0.5883],
        [0.1394, 0.4786, 0.5617],
        [0.3064, 0.2662, 0.0324]])

In [47]:
mat_mul.shape

torch.Size([3, 3])

In [48]:
#This is 3 dimensional matrix

Solution for the shape problem is to convert it to the Transpose matrix

In [49]:
tensor_A = torch.tensor([[1,2],
                          [4,5],
                          [6,7]])

In [50]:
tensor_B = torch.tensor([[7,8],
                          [9,10],
                          [11,12]])

In [51]:
#torch.matmul(tensor_A,tensor_B)

In [52]:
tensor_B_Transpose = tensor_B.T

In [53]:
torch.matmul(tensor_A,tensor_B_Transpose)

tensor([[ 23,  29,  35],
        [ 68,  86, 104],
        [ 98, 124, 150]])

In [54]:
tensor_A.shape

torch.Size([3, 2])

In [55]:
tensor_B_Transpose.shape

torch.Size([2, 3])

The matrix multiplication works when tensor_B is transposed

In [56]:
print(f"Original shapes : tensor_A = {tensor_A.shape} , tensor_B = {tensor_B.shape}")
print(f"New shapes : tensor_A = {tensor_A.shape} (Same shape as above), tensor_B = {tensor_B.T.shape}")
print(f"Multiplying : {tensor_A.shape} * {tensor_B.T.shape}")
print("\n")
print("Output : ","\n")
output = torch.matmul(tensor_A , tensor_B.T)
print(output)
print("\n")
print(f"Output shape : {output.shape}")

Original shapes : tensor_A = torch.Size([3, 2]) , tensor_B = torch.Size([3, 2])
New shapes : tensor_A = torch.Size([3, 2]) (Same shape as above), tensor_B = torch.Size([2, 3])
Multiplying : torch.Size([3, 2]) * torch.Size([2, 3])


Output :  

tensor([[ 23,  29,  35],
        [ 68,  86, 104],
        [ 98, 124, 150]])


Output shape : torch.Size([3, 3])


#Tensor aggregation

In [57]:
x = torch.arange(0,101,10)

In [58]:
x

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [59]:
#Find the mean
torch.min(x) , x.min()

(tensor(0), tensor(0))

In [60]:
#Find the max
torch.max(x) , x.max()

(tensor(100), tensor(100))

In [61]:
#Find the sum
torch.sum(x) , x.sum()

(tensor(550), tensor(550))

In [62]:
#Find the mean , if we want to use mean in pytorch we want to convert into float first
torch.mean(x.type(torch.float32)) , x.type(torch.float32).mean()

(tensor(50.), tensor(50.))

#Finding the positional min and max

The positional args gives us the index instead of the specified statement

In [63]:
x = torch.arange(0,201,20)
x

tensor([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180, 200])

In [64]:
#Find the maximum index
torch.argmax(x) , x.argmax()

(tensor(10), tensor(10))

In [65]:
#Finding the minimum index
torch.argmin(x) , x.argmin()

(tensor(0), tensor(0))

In [66]:
#Random access of the element by specifying the index
x[9]

tensor(180)

#Reshaping , stacking , squeezing , unsqueezing

* Reshaping : Reshapes an input tensors to an defined shape

* view : It reshapes the input tensors but in memory the original tensor will be there

* Stacking : Combine the multiple tensors on top of each other (v stack) or side by side (h stack)

* Squeezing : Remove the "1" dimensions from a tensor

* Unsqueezing : Add "1" dimensions to a target tensor

* Permute : Return a view of the input with dimensions permuted(swapped) in  a certain way

Reshape

In [67]:
x = torch.arange(1,11)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
x_reshape = x.reshape(10,1)
x_reshape

tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]])

In [69]:
x.reshape(2,5)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [70]:

x.reshape(5,2)

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])

View

In [71]:
y = x.view(2,5)

In [72]:
y

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [73]:
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
y

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [75]:
y[:,0] = 11

In [76]:
#Changing the value of y changes in the result of x (because a view of a tensor shares the same memory as the original tensor)
x

tensor([11,  2,  3,  4,  5, 11,  7,  8,  9, 10])

Stack

In [77]:
y[:,0] = 1

In [78]:
x

tensor([ 1,  2,  3,  4,  5,  1,  7,  8,  9, 10])

v stack

In [79]:
x_stacked = torch.stack([x,x,x,x],dim = 0)
x_stacked

tensor([[ 1,  2,  3,  4,  5,  1,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  1,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  1,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  1,  7,  8,  9, 10]])

h stack

In [80]:
x_stacked_1 = torch.stack([x,x,x,x],dim = 1)
x_stacked_1

tensor([[ 1,  1,  1,  1],
        [ 2,  2,  2,  2],
        [ 3,  3,  3,  3],
        [ 4,  4,  4,  4],
        [ 5,  5,  5,  5],
        [ 1,  1,  1,  1],
        [ 7,  7,  7,  7],
        [ 8,  8,  8,  8],
        [ 9,  9,  9,  9],
        [10, 10, 10, 10]])

Squeeze

It is used to remove the 1 dimension in the shape of the tensor

In [81]:
x_reshaped = x.reshape(1,10)
x_reshaped

tensor([[ 1,  2,  3,  4,  5,  1,  7,  8,  9, 10]])

In [82]:
x_reshaped.squeeze()

tensor([ 1,  2,  3,  4,  5,  1,  7,  8,  9, 10])

In [83]:
x_reshaped.squeeze().shape

torch.Size([10])

We can see that when we had removed the 1 dimensional in the tensor

In [84]:
x_reshaped.unsqueeze(dim = 0)

tensor([[[ 1,  2,  3,  4,  5,  1,  7,  8,  9, 10]]])

In [85]:
x_reshaped.shape

torch.Size([1, 10])

Permute

In [86]:
# torch.permute - rearranges the dimensions of a target tensor in  a specified order


In [87]:
x_original = torch.rand(size=(3,1,3))
x_original

tensor([[[0.9599, 0.0031, 0.0946]],

        [[0.3803, 0.7762, 0.7636]],

        [[0.3017, 0.5324, 0.5253]]])

In [88]:
x_original = torch.rand(size=(3,2,3))
x_original

tensor([[[0.8225, 0.6635, 0.1640],
         [0.1210, 0.4874, 0.6788]],

        [[0.1823, 0.1271, 0.0637],
         [0.6619, 0.4387, 0.4211]],

        [[0.7857, 0.4334, 0.9369],
         [0.2073, 0.4773, 0.5430]]])

In [89]:
x_original = torch.rand(size=(3,3,3))
x_original

tensor([[[0.4697, 0.4287, 0.1003],
         [0.6759, 0.6481, 0.6250],
         [0.0269, 0.0668, 0.6643]],

        [[0.6055, 0.6025, 0.2910],
         [0.8925, 0.1720, 0.2787],
         [0.2100, 0.8838, 0.5693]],

        [[0.0246, 0.5939, 0.2730],
         [0.7586, 0.8464, 0.8609],
         [0.5338, 0.3019, 0.1295]]])

In [90]:
x_original = torch.rand(size=(224,224,3))
x_permuted = x_original.permute(2,0,1)
x_permuted
print(f"Size of the original tensor {x_original.shape}")
print(f"Size of the permutted tensor {x_permuted.shape}")

Size of the original tensor torch.Size([224, 224, 3])
Size of the permutted tensor torch.Size([3, 224, 224])


#Indexing

In [91]:
import torch


In [92]:
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [93]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [94]:
x[0][0]

tensor([1, 2, 3])

In [95]:
x[0,2,2]

tensor(9)

In [96]:
x[:,:,0]

tensor([[1, 4, 7]])

In [97]:
x[:,1,2]

tensor([6])

In [98]:
x[0,0,:]

tensor([1, 2, 3])

In [99]:
x[0,2,2]

tensor(9)

In [100]:
x[:,:,2]

tensor([[3, 6, 9]])

#Pytorch tensors & Numpy

Numpy is a popular scientific Python numerical computing Library so because of this reason Pytorch has the functionality to interact with it

* Pytorch tensor -> Numpy -> torch.Tensor.numpy()
* Numpy -> Pytorch -> torch.from_numpy(ndarray)



In [101]:
#Now we can use it
import numpy as np
import torch

In [102]:
x = np.arange(0,11)
y = torch.from_numpy(x)
x , y

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [103]:
# Converting pytorch to numpy
x = torch.arange(1,11)
y = torch.Tensor.numpy(x)
x , y

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

#Reproducability (Trying to take random out of random)

To reduce the randomness in neural networks and pytorch comes to the concept of a **random seed**

In [104]:
x = torch.rand(3,2)
y = torch.rand(3,2)
x , y
print(x == y)

tensor([[False, False],
        [False, False],
        [False, False]])


In [105]:
x

tensor([[0.2521, 0.3239],
        [0.9107, 0.0895],
        [0.7183, 0.7218]])

In [106]:
y

tensor([[0.9131, 0.7978],
        [0.6044, 0.4620],
        [0.9667, 0.3511]])

In [107]:
#We could know that x and y are not equal as random value will change everytime

In [108]:
#We can try to use randomseed

In [109]:
random_seed = 42
torch.manual_seed(random_seed)
x = torch.rand(2,2)

torch.manual_seed(random_seed)
y = torch.rand(2,2)

print(x == y)

tensor([[True, True],
        [True, True]])


We could understand that Random_seed is much usable for the Reproducability

#Running Tensors and PyTorch objects on the GPU's (and making faster computations)

In [110]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [111]:
#Check for GPU access with Pytorch
import torch
torch.cuda.is_available()

False

In [112]:
device = "cuda"  if torch.cuda.is_available() else "cpu"
device

'cpu'